import pandas as pd # data manipulation
import os # operating system interfaces
import time # time-related functions
import pickle # object serialization
import numpy as np # numerical computing

import torch # tensor library and deep learning
import torch.nn as nn # neural network modules
import torch.optim as optim # optimization algorithms
from torch.utils.data import Dataset, DataLoader # data handling
from sklearn.preprocessing import LabelEncoder # encoding categorical labels
from sklearn.metrics import mean_squared_error, mean_absolute_error # model evaluation metrics


class MovieLensDataset(Dataset):
    """
    Encapsulates MovieLens data for PyTorch DataLoaders.
    Converts user indices, item indices, explicit genres, and ratings into tensors.
    """
    def __init__(self, users, items, genres, ratings):
        self.users = torch.tensor(users, dtype=torch.long)
        self.items = torch.tensor(items, dtype=torch.long)
        self.genres = torch.tensor(genres, dtype=torch.float32) # Added genre tensor
        self.ratings = torch.tensor(ratings, dtype=torch.float32)

    def __len__(self):
        return len(self.ratings)

    def __getitem__(self, idx):
        # Now returns 4 elements per batch
        return self.users[idx], self.items[idx], self.genres[idx], self.ratings[idx]


class ExplainableNeuMF(nn.Module):
    """
    Context-Aware Neural Matrix Factorization.
    """
    def __init__(self, num_users, num_items, num_genres, embed_size=64):
        super().__init__()

        # Embedding layers with +1 buffer to accommodate the Unknown (UNK) token
        self.user_embed = nn.Embedding(num_users + 1, embed_size)
        self.item_embed = nn.Embedding(num_items + 1, embed_size)

        # MLP Pipeline: Processes concatenated user-item embeddings
        self.mlp_pipeline = nn.Sequential(
            nn.Linear(embed_size * 2, 64),
            nn.BatchNorm1d(64),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(64, 32),
            nn.BatchNorm1d(32),
            nn.ReLU()
        )

        # Final layer dynamically accepts the GMF, MLP, AND the explicit genre features
        self.output = nn.Linear(embed_size + 32 + num_genres, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, user_indices, item_indices, explicit_genres):
        u = self.user_embed(user_indices)
        i = self.item_embed(item_indices)

        # GMF Pathway
        gmf_vector = u * i
        
        # MLP Pathway
        mlp_vector = self.mlp_pipeline(torch.cat([u, i], dim=1))

        # WIDE & DEEP CONCATENATION: Deep features + Human-readable explicit genres
        combined_vector = torch.cat([gmf_vector, mlp_vector, explicit_genres], dim=1)
        prediction = self.output(combined_vector)

        # Scaling: Transforms 0-1 sigmoid range to 0.5-5.0 rating scale
        return (self.sigmoid(prediction) * 4.5 + 0.5).squeeze()


def safe_transform(encoder, values):
    """
    Label encoding that maps unseen values in the test set to an 'UNK' (0) index.
    """
    mapping = {k: i + 1 for i, k in enumerate(encoder.classes_)}
    return np.array([mapping.get(v, 0) for v in values])


def prepare_split(df):
    """
    Temporal per-user split. 
    Allocates the first 80% of a user's history to training and the final 20% to testing.
    """
    df = df.sort_values(['userId', 'datetime'])
    df['rank'] = df.groupby('userId').cumcount()
    df['count'] = df.groupby('userId')['userId'].transform('count')

    train_df = df[df['rank'] < df['count'] * 0.8].copy()
    test_df = df[df['rank'] >= df['count'] * 0.8].copy()

    return train_df, test_df


def extract_genre_features(df):
    """
    Helper function to dynamically identify the new genre columns
    by filtering out the standard metadata columns.
    """
    standard_cols = ['userId', 'movieId', 'rating', 'timestamp', 'datetime', 'title', 'rank', 'count']
    genre_cols = [col for col in df.columns if col not in standard_cols]
    return genre_cols


def train_hybrid_model(epochs=10, batch_size=2048):
    """
    Orchestrates the model training process for the Explainable network.
    """
    current_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(current_dir)

    processed_dir = os.path.join(project_root, 'data', 'processed')
    models_dir = os.path.join(project_root, 'models')
    os.makedirs(models_dir, exist_ok=True)

    parquet_path = os.path.join(processed_dir, 'master_data_small.parquet')
    global_df = pd.read_parquet(parquet_path)

    # Automatically detect the binary genre columns generated by the data pipeline
    genre_cols = extract_genre_features(global_df)
    num_genres = len(genre_cols)

    train_df, test_df = prepare_split(global_df)

    user_encoder = LabelEncoder()
    item_encoder = LabelEncoder()

    user_encoder.fit(train_df['userId'])
    item_encoder.fit(train_df['movieId'])

    with open(os.path.join(models_dir, 'user_encoder.pkl'), 'wb') as f:
        pickle.dump(user_encoder, f)
    with open(os.path.join(models_dir, 'item_encoder.pkl'), 'wb') as f:
        pickle.dump(item_encoder, f)
    
    # Save the specific genre column names so the Inference Engine knows them later
    with open(os.path.join(models_dir, 'genre_cols.pkl'), 'wb') as f:
        pickle.dump(genre_cols, f)

    train_users = safe_transform(user_encoder, train_df['userId'])
    train_items = safe_transform(item_encoder, train_df['movieId'])
    train_genres = train_df[genre_cols].values # Extract the 1s and 0s matrix

    num_users = len(user_encoder.classes_)
    num_items = len(item_encoder.classes_)

    # Inject the genres into the Dataset
    train_dataset = MovieLensDataset(train_users, train_items, train_genres, train_df['rating'].values)
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Training on {device} | Users: {num_users} | Movies: {num_items} | Genres: {num_genres}")

    # Boot the new Explainable architecture
    model = ExplainableNeuMF(num_users, num_items, num_genres).to(device)

    criterion = nn.SmoothL1Loss()
    optimizer = optim.Adam(model.parameters(), lr=0.002)

    for epoch in range(epochs):
        model.train()
        total_loss = 0
        start_time = time.time()

        # Unpack the 4 distinct elements from the new Dataloader
        for batch_idx, (users, items, genres, ratings) in enumerate(train_loader):
            users = users.to(device)
            items = items.to(device)
            genres = genres.to(device)
            ratings = ratings.to(device)

            optimizer.zero_grad()
            
            # Pass the 3 features to the forward function
            predictions = model(users, items, genres)
            
            loss = criterion(predictions, ratings)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        avg_train_loss = total_loss / len(train_loader)
        print(f"Epoch {epoch+1}/{epochs} | Loss: {avg_train_loss:.4f} | Time: {time.time() - start_time:.2f}s")

    torch.save(model.state_dict(), os.path.join(models_dir, 'neumf_model_small.pth'))


def evaluate_cf_model(batch_size=2048):
    """
    Performs evaluation on the test set for the Explainable network.
    """
    print("Loading test data and trained model")

    current_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(current_dir)

    processed_dir = os.path.join(project_root, 'data', 'processed')
    models_dir = os.path.join(project_root, 'models')

    parquet_path = os.path.join(processed_dir, 'master_data_small.parquet')
    global_df = pd.read_parquet(parquet_path)

    with open(os.path.join(models_dir, 'user_encoder.pkl'), 'rb') as f:
        user_encoder = pickle.load(f)
    with open(os.path.join(models_dir, 'item_encoder.pkl'), 'rb') as f:
        item_encoder = pickle.load(f)
    
    # Load the genre column names to ensure strict alignment
    with open(os.path.join(models_dir, 'genre_cols.pkl'), 'rb') as f:
        genre_cols = pickle.load(f)

    num_genres = len(genre_cols)

    train_df, test_df = prepare_split(global_df)

    test_users = safe_transform(user_encoder, test_df['userId'])
    test_items = safe_transform(item_encoder, test_df['movieId'])
    test_genres = test_df[genre_cols].values

    num_users = len(user_encoder.classes_)
    num_items = len(item_encoder.classes_)

    test_dataset = MovieLensDataset(test_users, test_items, test_genres, test_df['rating'].values)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = ExplainableNeuMF(num_users, num_items, num_genres).to(device)

    model_path = os.path.join(models_dir, 'neumf_model_small.pth')
    model.load_state_dict(torch.load(model_path, weights_only=True))
    model.eval()

    actuals = []
    predictions = []

    print("Running predictions")

    with torch.no_grad(): 
        # Unpack the 4 elements during testing as well
        for users, items, genres, ratings in test_loader:
            users = users.to(device)
            items = items.to(device)
            genres = genres.to(device)
            
            # Predict using all 3 features
            preds = model(users, items, genres).cpu().numpy()

            predictions.extend(preds)
            actuals.extend(ratings.numpy())

    rmse = np.sqrt(mean_squared_error(actuals, predictions))
    mae = mean_absolute_error(actuals, predictions)

    print("\n========================================")
    print("EVALUATION RESULTS")
    print("========================================")
    print(f"RMSE: {rmse:.4f}")
    print(f"MAE : {mae:.4f}")
    print("========================================\n")